name: EC2 Deploy
#run on 
on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.4.0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build


  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY } }
      REMOTE_HOST: ${ { secrets.HOST_DNS } }
      REMOTE_USER: ${ { secrets.USERNAME } }
    steps:
    - name: Deploy to Server 1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.REMOTE_HOST }}
        username: ${{ env.REMOTE_USER }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd /home/ubuntu/aflat-web-server
          git pull
          npm install
          npm run build
          pm2 restart all
