name: EC2 Deploy
#run on 
on: [workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.4.0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  # deploy:
  #   name: Deploy to EC2
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the files
  #       uses: actions/checkout@v2
  #     - name: Deploy to Server 1
  #     env:
  #       SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY } }
  #       REMOTE_HOST: ${ { secrets.HOST_DNS } }
  #       REMOTE_USER: ${ { secrets.USERNAME } }
  #       TARGET: ${ { secrets.TARGET_DIR } }
