name: EC2 Deploy
#run on push workflow_dispatch pull_request to main branch 
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-express:
    name: Build Express
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.4.0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  build-aflat:
    name: Build and push Aflat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker-compose build
      - name: Push Docker image
        run: docker push deforestt/aflat:latest

  deploy:
    needs: [build-express, build-aflat]
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Server 1
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key

        ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} 'bash ~/deploy.sh'
