name: NODE CI
#run on 
on: [workflow_dispatch, pull_request]

jobs:
  build-aflat:
    name: Build Aflat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker-compose build
  build-express:
    name: Build Express
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17.4.0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
